### PR TITLE
Fix spelling errors

### PR DESCRIPTION
**Pull request by dforsi**
This PR fixes some trivial spelling errors found semi-automatically using codespell.

Fixed with:
codespell --ignore-words-list ans,conect,co-ordinate,co-ordinates,cppp,ist,nd,sav,tha,tht --interactive 2 --write-changes

### CODE REVIEW

**Comment by dforsi** [comment]
I didn't change "conect" to "connect" because it is the name of a function.

**Comment by KJ7LNW** [comment]
Merged, thank you!  Also good catch about conect vs connect.  I'm not sure if that should change or not.  This came from FORTRAN so if the original fortran function was "conect" then it should remain.

**Comment by dforsi** [comment]
> Merged, thank you!

great

>  Also good catch about conect vs connect. I'm not sure if that should change or not.
> This came from FORTRAN so if the original fortran function was "conect" then it should remain.

you are right and indeed the FORTRAN sources for nec2-1.2.1.2.f here
https://www.qsl.net/m5aiq/nec.html show the same so it's better to
keep unchanged.

The FORTRAN code:

      SUBROUTINE CONECT( IGND)
C ***
      IMPLICIT REAL (A-H,O-Z)
C
C     CONNECT SETS UP SEGMENT CONNECTION DATA IN ARRAYS ICON1 AND ICON2
C     BY SEARCHING FOR SEGMENT ENDS THAT ARE IN CONTACT.
C

The C code:

/* connect sets up segment connection data in arrays icon1 and */
/* icon2 by searching for segment ends that are in contact. */
 gboolean
conect( int ignd )

-- 
Daniele Forsi

**Comment by KJ7LNW** [comment]
Awesome, thanks for checking that.

What type of work do you do with xnec2c?  Do you have a ham license and call sign?

If you design antennas, then I would love some feedback on xnec2c-optimize: https://github.com/KJ7LNW/xnec2c-optimize

**Comment by dforsi** [comment]
> What type of work do you do with xnec2c?

well, I use it only as a viewer for files

> Do you have a ham license and call sign?

yes, my callsign is IU5HKX

> If you design antennas, then I would love some feedback on xnec2c-optimize: https://github.com/KJ7LNW/xnec2c-optimize

I don't design antennas but I'll share the link with some hams that
might be interested.

The only feedback that I can give right now is:
1. For people like me (not native speakers and not antenna designers)
it could be useful to explain why "an optimization framework to tune
antenna geometries" is useful, so if I meet someone who has a problem
that can be solved with xnec2c-optimize, I can tell them to use it

2. For people like me :-) (not familiar with Perl) more details about
installation could be useful, such as the exact commands to paste in a
terminal; at first I didn't understand that "cpanm PDL" is an actual
command, even if it's correctly styled.

**Comment by KJ7LNW** [comment]
Ok I updated the readme to be more clear, check it out:

https://github.com/KJ7LNW/xnec2c-optimize#examples

**Comment by KJ7LNW** [comment]
Oops, without the anchor:
   https://github.com/KJ7LNW/xnec2c-optimize

**Comment by dforsi** [comment]
> https://github.com/KJ7LNW/xnec2c-optimize

very good, thank you

**Pull request merged**
